### ISSUE TITLE
Where to get DSPIO.h ?

### ISSUE THREAD

**Issue by maolintao** [MajenkoLibraries/nrf24l01#1]
Where to get DSPIO.h ?

**Comment by majenkotech** [comment]
There is no DSPIO.h.  There is DSPI.h, which is a standard chipKIT library included with MPIDE and the UECIDE chipKIT core.  There's nothing to "get".

**Comment by maolintao** [comment]
thank you,and,if this ‘nrf24l01’ can run on arduino?DSPI.h has not find in arduino IDE

**Comment by majenkotech** [comment]
No, it does not work on the Arduino. It is for the chipKIT boards not the Arduino boards.
